### ISSUE TITLE
Getting 404 after logging into Client

### ISSUE THREAD

**Issue by kcrowe123** [vojtechruz/spring-boot-admin#9]
I was trying to follow along with tutorial for spring-boot-admin client/server.  After logging into Admin Server I see my client, I click link and login to client.  Then I get 404 error page.  I was kind of at a loss so I just cloned repo and just tried to run it as-is and got the same thing.  This is on the master branch.

**Comment by vojtechruz** [comment]
It is a bit confusing - but in the spring boot admin, it matters where you click:
- if you click on the URL, it will navigate it from your admin to the monitored application itself
- if you click not on the URL, it will show the detail of the monitored application in spring boot admin

This is confusing as most of the time you want to show monitoring data and not navigate to the application itself, but it looks like only the URL is clickable.

The reason why you see 404 is because you clicked on the URL and it takes you to the monitored application instead of spring boot admin detailed view. Because the client application is just for demo purposes of monitoring, it does not have any pages and therefore you get 404 after logging in.

It is a bit confusing, does it makes sense? :) Did this help?

**Comment by kcrowe123** [comment]
Yes it worked!  Thank you for quick response.

**Comment by vojtechruz** [comment]
Cool, no problem :) Closing the issue.
